name: analysis3
channels:
- coecms
- conda-forge
- scitools
dependencies:
- python=3
- coecms-nci
- cdo
- basemap
- cartopy
- dask
- distributed
- ipython
- iris
- netCDF4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- pybufr-ecmwf
- jupyter
- notebook
- plotly
- nchash
- yamanifest>=0.3.2
- cmocean
- nccompress>=0.1.4
- zarr
- pytables
- nose
- ncdu
- cftime # Missing dependency of pyart
- memory_profiler
- mdssdiff
- fs>=2.0.24
- python-magic
- dataset
