name: analysis3
channels:
- coecms
- conda-forge
dependencies:
- python=3
- coecms-nci
- cdo
- hdf5
- basemap
- cartopy
- dask
- distributed
- ipython
- iris
- netCDF4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy=1.2.1 # 1.3.0 incompatible with statsmodels https://github.com/statsmodels/statsmodels/issues/5759
- seaborn
- xarray
- pybufr-ecmwf
- jupyter
- notebook
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh
- datashader
- f90nml
- wrf-python
- sympy
- sh
- basemap-data-hires
- dataset
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- umtools
- compliance-checker
- xerces-c
- ncimonitor
- plotly
- nchash
- yamanifest
- cmocean
- nccompress
- zarr
- pytables
- nose
- ncdu
- cftime # Missing dependency of pyart
- memory_profiler
- mdssdiff
- fs
- python-magic
- click_default_group
- regionmask
- libgdal
- matplotlib
- dreqpy
- pint
- pycodestyle
- nc-time-axis
- jq
- pvlib-python
- parcels
- siphon
- scikit-learn
- filelock
- cosima-cookbook
- gsw
- nb_conda_kernels
- poppler
- fiona>1.8
- sanic 
- hupper
- kealib
- mo_pack
- mule
- cf_units
- python-stratify
- nbdime
- eofs
- matplotlib-venn
- mnctools
- payu
- dusql
- splitvar
- python-eccodes
- h5py
- clef
- line_profiler
- nccmp
- bottleneck
- coecms-util
- jupyterlab
- dask-jobqueue
- jupyterlab_server
- docrep
- dask-labextension
- jupyter_nbextensions_configurator
- nodejs
- cfgrib
- h5netcdf
- jupyter_contrib_nbextensions
- intake
# Can be removed when pinning no longer required
- tornado=5.1.1 # To get dask-labextension working
