name: analysis3
channels:
- coecms
- conda-forge
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/hh5/public/apps/cartopy-data/backgrounds
dependencies:
- python>=3.9
- pip<22.0 # error with import railroad
###########
# Resolve issues before removing these pins
- sqlalchemy<1.4 # https://github.com/coecms/conda-envs/issues/25
###########
- libnetcdf>=4.7.4=mpi_openmpi* # pinned for solver stability
- coecms-nci
- cdo>=1.9.5 # pinned for solver stability
- hdf5
 #x basemap # Deprecated, see https://matplotlib.org/basemap/users/intro.html#deprecation-notice
 #x basemap-data-hires
- cartopy>=0.19 # pinned for solver stability
- dask
- distributed
- ipython
- iris
- netcdf4
- numpy>=1.21 # Mule dependency
- pandas<1.4.0
- pygrib
- pyhdf
- pytest
- scipy<=1.8.0
- seaborn
- xarray
- jupyter
- notebook
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh
- datashader
- f90nml
- wrf-python
- sympy
- sh
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- compliance-checker
- dataset
- xerces-c
- plotly
- zarr
- pytables
- nose
- ncdu
- cftime
- cfunits
- memory_profiler
- fs
- python-magic
- click_default_group
- regionmask
- rasterio>=1.2.10           # pinned to solve #37
- gxx_linux-64               # add missing dependency for #37
- gdal<3.4.2                # pinned for solver stability and rasterio incompatibility #37
- libgdal<3.4.2             # pinned for solver stability and rasterio incompatibility #37
- matplotlib>=3.5.2|<=3.4.3  # pinned to solve  https://github.com/matplotlib/matplotlib/issues/21917
- dreqpy
- pint
- pycodestyle
- nc-time-axis
- jq
- pvlib-python
- parcels>=2.3.0            # Pin to force update
- siphon
- scikit-learn
- filelock
- gsw
- nb_conda_kernels
- poppler
- fiona
- hupper
- kealib
- mo_pack
- mule
- cf-units
- python-stratify
- nbdime
- eofs
- eccodes
- python-eccodes
- h5py
- line_profiler
- bottleneck
- jupyterlab
- dask-jobqueue
- jupyterlab_server
- docrep
- gifsicle
- jupyter_nbextensions_configurator
- nodejs
- cfgrib
- h5netcdf
- jupyter_contrib_nbextensions
- intake
- gridfill
- xgcm>0.5 # pinned for solver stability
- xrft
- doit
- pylint
- dusqlpg
- matplotlib-venn
- nchash
- umtools
- cosima-cookbook
- clef
- nccmp
- coecms-util
- yamanifest
- cmocean
- payu
- splitvar
- marineHeatWaves
- holoviews<1.14.8
- pytest-cov
- panel
- xrft
- git
- openmpi<=4.1.2
- mpi4py
- palettable
- xlrd
- nccompress
- mdssdiff
- mnctools
- addmeta
- satpy
- statsmodels
- dask-labextension
- nbstripout
- jupyter-server-proxy
- sphinx
- doc8
- pymunge
- climtas
- asyncssh
- ants
- xhistogram
- cartopy_userconfig=1.0.gadi
- geopy
- ninja
- hvplot
- cython
- esmf>=8.0.1=mpi_openmpi*
- esmpy>=8.0.1=mpi_openmpi*
- xesmf>=0.6.2 # https://github.com/pangeo-data/xESMF/issues/127
- sharppy
- docrep
- earthpy
- descartes
- era5grib
- conda-tree
- xmitgcm
- cupy
- rioxarray
- rasterstats
- windrose
- pyam
- pyarrow
- python-gist
- celluloid
- jags
- xarray-spatial
- nctoolkit
- geoplot
- dask-ml>=2022.5.27
- mamba<=0.23.0  # pin to solve error with missing libmamba library
- intake-esm
- pykrige
- nci_intake_catalogue
- cmdline_provenance
- mplleaflet
- branca
- fiona
- folium
- black
- aiohttp
- aiohttp-cors
- autopep8
- spyder-kernels
- dask-xgboost
- git-subtree
- xarray-spatial
- watermark
- cvxpy
- rechunker
- xmovie
- pymannkendall
- param
- noise # unlisted dependency of xarray-spatial
- tensorflow>=2.6 # pinned for solver stability
- shap 
- gh
- pyqt
- vtk
- mayavi
- gcm_filters
- timezonefinder
- lftp
- xarraymannkendall
- watchdog  
- numpy_groupies
- anytree
- fortran-language-server
- hdbscan
- jupyter-book
- iris-grib
- s3fs
- kerchunk
- ujson
- intake-thredds
- cafaz
- cdms2
- pygam
- pysal
- xmhw
- argopy
- dataclasses-json
- ilamb
- posix_ipc
- spectrum
- arch-py
- pyextremes
- ipdb
- palettable
- webcolors
- mpl-scatter-density
- benchcab
- lmfit
- xclim
- jupyter-resource-usage
