name: analysis3
channels:
- coecms
- conda-forge
dependencies:
- python>=3.8
- coecms-nci
- cdo
- hdf5
 #x basemap # Deprecated, see https://matplotlib.org/basemap/users/intro.html#deprecation-notice
 #x basemap-data-hires
- cartopy
- dask
- distributed
- ipython
- iris=2.4.0
- netcdf4
- numpy
- pandas
- pygrib
- pyhdf
- pytest
- scipy
- seaborn
- xarray
- jupyter
- notebook
- nb_conda
- metpy
- windspharm
- python-cdo
- arm_pyart
- bokeh
- datashader
- f90nml
- wrf-python
- sympy
- sh
- ffmpeg
- pydap
- twine
- python-graphviz
- joblib
- tqdm
- compliance-checker
- dataset
- xerces-c
- plotly
- zarr
- pytables
- nose
- ncdu
- cftime<1.3.0 # Error with year=0 dates in 1.3.0
- memory_profiler
- fs
- python-magic
- click_default_group
- regionmask
- libgdal
- matplotlib
- dreqpy
- pint
- pycodestyle
- nc-time-axis
- jq
- pvlib-python
- parcels
- siphon
- scikit-learn
- filelock
- gsw
- nb_conda_kernels
- poppler
- fiona
- hupper
- kealib
- mo_pack
- mule
- cf-units
- python-stratify
- nbdime
- eofs
- eccodes
- python-eccodes<2021.01
- h5py
- line_profiler
- bottleneck
- jupyterlab
- dask-jobqueue
- jupyterlab_server
- docrep
- gifsicle
- jupyter_nbextensions_configurator
- nodejs
- cfgrib
- h5netcdf
- jupyter_contrib_nbextensions
- intake
- pyngl
  # - pynio # Wants HDF5 < 1.10.6
- gridfill
- pyferret
- xgcm
- xrft
- doit
- pylint
- dusqlpg
- matplotlib-venn
- ncimonitor=0.3.6   # Pin to this version for general NCI use. Later versions are for grafana
- nchash
- umtools
- cosima-cookbook
- clef
- nccmp
- coecms-util
- yamanifest
- cmocean
- payu
- splitvar
- marineHeatWaves
- holoviews
- pytest-cov
- panel
- xrft
- git
- openmpi=*=gadi_* # Loads openmpi module on gadi
- mpi4py
- palettable
- xlrd
  #- pybufr-ecmwf # Error compiling for python 3.7
- nccompress
- mdssdiff
- mnctools
- addmeta
- satpy
- statsmodels>=0.11.0
- dask-labextension
- nbstripout
- jupyter-server-proxy
- sphinx
- doc8
- pymunge
- climtas
- asyncssh
- ants
- xhistogram
- cartopy_userconfig=1.0.gadi
- geopy
- ninja
- hvplot
- cython
- esmpy=*=gadi
- xesmf
- sharppy
- docrep
- earthpy
- descartes
- era5grib
- conda-tree
- xmitgcm
- cupy
- rioxarray
- rasterstats
- windrose
- pyam
- pyarrow
- python-gist
  #- celluloid
- jags
- xarray-spatial
- nctoolkit
- geoplot
