# Modules test will not try to import
skip:
# Cause errors and don't throw exceptions cleanly
- psutil.tests
- pandas.io.clipboard
- matplotlib.backends
- pbr.tests
- plotly.plotly
- bokeh.server.django
# Too many, or not necessary
- iris.tests
- cartopy.tests
- plotly.validators
- xarray.tests
- pyresample.test
- pyferret.eofanal
- ants.tests
- alembic.testing
- sqlalchemy.testing
- httpx
- sanic
- tests # random tests from black?
  # - cupy # Disable when testing locally
  # - cupyx # ditto
  # - nci_intake_catalogue # ditto
- wrf # Prints garbage at v1.3.2.5
- matplotlib.tests # No test data
- prometheus_client.twisted # No twisted

# Preload these modules before testing to avoid weird python issues
preload:
- pysal
- tables
- skimage.data
- sklearn
- sklearn.covariance
- sklearn.manifold
- stratify
- xarray

# Allow loading, but pass exceptions. When exceptions no longer triggered
# can remove
exception:
- sqlalchemy.testing.suite
- zmq.green
- prometheus_client.twisted
- sqlalchemy.testing.suite
- zmq.backend.cffi
- sklearn.mixture
- matplotlib.tests
- metpy.io     # While Issue #21 unresolved
- metpy.plots  # While Issue #21 unresolved
- httpx
- sanic
